displayName=Double-Click Deposit Worn Items
author=JNettli
description=A plugin to stop you from accidentally depositing your worn items
tags=bank,safety,deposit,qol
plugins=com.example.PluginLauncher